flow transactions build ./flow-multisig/scripts/testnet-acct-creation.cdc \
  --network testnet \
  --args-json "$(cat "./flow-multisig/scripts/args.json")" \
  --proposer authorizer \
  --proposer-key-index 0 \
  --authorizer authorizer \
  --payer authorizer \
  --gas-limit 1000 \
  --yes \
  -x payload \
  --save ./flow-multisig/scripts/create-account.rlp